// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleteAllUser.sql

package database

import (
	"context"
)

const deleteUsers = `-- name: DeleteUsers :one
DELETE FROM users RETURNING id, name, created_at, updated_at
`

func (q *Queries) DeleteUsers(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, deleteUsers)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
