// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getPostsForUser.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT
    p.id,
    p.title,
    p.description,
    p.url,
    p.published_at,
    f.name AS feed_name
FROM
    posts p 
    INNER JOIN feed_follows ff ON ff.feed_id = p.feed_id
    INNER JOIN feeds f ON f.id = p.feed_id
WHERE 
    ff.user_id = $1
ORDER BY 
    p.published_at DESC 
LIMIT $2
`

type GetPostsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

type GetPostsForUserRow struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Url         string
	PublishedAt sql.NullTime
	FeedName    string
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]GetPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.PublishedAt,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
